#!/usr/bin/python3
from sys import argv
from math import ceil, sqrt

class FactorisationError(Exception):
    pass

def exhaustive_factorisation(N):
    n = 3
    while N % n != 0:
        n += 2
        if n > 1000000:
            raise TimeoutError
    return (N // n, n)

def fermat_factorisation(N):
    if N % 2 == 0:
        return  (N // 2, 2)
    a = ceil(sqrt(N))
    b2 =  a*a - N
    while int(sqrt(b2)) != sqrt(b2):
        a = a + 1
        b2 = a*a - N
    return (int(a + sqrt(b2)), int(a - sqrt(b2)))

if __name__ == '__main__':
    if len(argv) < 2:
        raise RuntimeError("Usage: ./factors")
    lines = open(argv[1]).readlines()
    for line in lines:
        print(line)
        num = int(line)
        f1, f2 = fermat_factorisation(num)
        print("{}={}*{}".format(num, f1, f2))
